<<<<<<< HEAD
// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("Hello World!");

export {
  
}
/*  Not a pure module */
=======
// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("Hello World!");

export {
  
}
/*  Not a pure module */
>>>>>>> 97290ea1dec511a994b804307bed581e1019c78d
