<<<<<<< HEAD
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NumberButton$Button(Props) {
  var count = Props.count;
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twiceeee"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("button", undefined, msg);
}

var Button = {
  make: NumberButton$Button
};

export {
  Button ,
}
/* react Not a pure module */
=======
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NumberButton$Button(Props) {
  var count = Props.count;
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twiceeee"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("button", undefined, msg);
}

var Button = {
  make: NumberButton$Button
};

export {
  Button ,
}
/* react Not a pure module */
>>>>>>> 97290ea1dec511a994b804307bed581e1019c78d
